name: Tests

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        php: [ 7.4, 8.0 ]
        dependency-version: [ prefer-lowest, prefer-stable ]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: soap

      - name: Install dependencies (PHP < 8)
        if: ${{ matrix.php != '8.0' }}
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      # Temporary, while dependencies are updated to support 8.O
      - name: Install dependencies (PHP >= 8)
        if: ${{ matrix.php == '8.0' }}
        run: composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest --ignore-platform-req=php

      - name: Execute tests
        run: make test

      - name: Execute PHPStan
        run: make phpstan

      - name: Execute Psalm
        run: make psalm
